version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.6.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10  # Adjust this based on your need

  selenium-node-chrome1:
    image: selenium/node-chrome:4.6.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10  # Set the maximum number of sessions per node
      - SE_NODE_PORT=5555
    depends_on:
      - selenium-hub
    ports:
      - "5555:5555"

  latest-articles-on-sections:
    build: .
    volumes:
      - .:/app
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
      - selenium-node-chrome1
    command: ["python", "/app/scripts/extract_latest_articles_on_sections.py"]
  
  highlighted-articles:
    build: .
    volumes:
      - .:/app
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
      - selenium-node-chrome1
    command: ["python", "/app/scripts/read_highlighted_articles.py"]

  

  